### ISSUE TITLE
Getting involved

### ISSUE THREAD

**Issue by BurtHarris** [eemeli/yaml-types#6]
This looks like a great project; I'd like to offer some help.     

I'm a retired dev, with typescript and YAML experience.   My background is at Microsoft.   I didn't see a discussion area yet, and though I could offer to chip in.   Let me know if you have any tasks I might help with.

**Comment by eemeli** [comment]
Hi, and welcome! Good point, I just enabled the discussion area.

I've no grand plan for this project; the core idea is to just start collecting a set of useful YAML types for JavaScript. Where it goes from there, I guess we'll find out?

**Comment by BurtHarris** [comment]
Excellent
